### ISSUE TITLE
Windows Installation 

### ISSUE THREAD

**Issue by thhowsif** [platform-experience/serviceportal-widget-library#79]
We try to open the application in windows machine. but, we don't know how to open the application. May I know that how to access the application. Share me the steps to run the application in Windows machine.

**Comment by stevengregory** [comment]
Hey @thhowsif, I'm not exactly sure what you're asking, because this repo doesn't provide any applications at this moment. The widget library provides a collection of reusable widgets for Service Portal distributed via update sets. The update sets are the mechanism for the installation into the target instance; which should be platform agnostic. Let us know if there is a problem with a specific widget; if that is what you're having issues with.
